name: Integration tests
on:
  push:

env:
  GOLANG_VERSION: "1.22.3"

jobs:
  build-go:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Download all Go modules
        run: go mod download
      - name: Compile all packages
        run: make build
      - name: Run local K3S cluster for tests
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: "latest"
      - name: Run all tests
        run: make test
